### ISSUE TITLE
Unable to launch on Mac

### ISSUE THREAD

**Issue by deboer-tim** [RuntimeTools/javametrics#45]
I'm trying to use the agent on a simple Java app on my Mac. It fails on startup with the following:

objc[85996]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java (0x1047a54c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10486d4e0). One of the two will be used. Which one is undefined.
Javametrics: Unable to start javaagent: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at com.ibm.javametrics.instrument.Agent.premain(Agent.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.ibm.javametrics.instrument.Agent$1.loadClass(Agent.java:93)
	... 11 more

**Comment by NikCanvin** [comment]
@tobespc @robbinspg @sjanuary 
please could one of you take an urgent look at this, and get back to Tim, ASAP

**Comment by tobespc** [comment]
@deboer-tim you don't have all the files you need.  The agent needs the asm directory with files in underneath the directory where you have the javametrics-agent in.  How are you installing this ?

**Comment by tobespc** [comment]
I've amended the README.md file to make this a bit clearer

NOTE, if you move the javametrics-agent to another directory you need to make sure you take the asm folder with it. The asm folder is required for the agent to run as it contains files that the agent needs

**Comment by deboer-tim** [comment]
IMHO most people will just want to download and use metrics, not clone git, do a build, run tests, and then copy the release out to use it. If I follow the Installation instructions or go directly to the release page (https://github.com/runtimetools/javametrics/releases), there's no mention of the asm dependency, how to get it, or where to put it relative to the agent.

Personally I'd prefer to see the release changed to a single archive that has two folders (agent and client/webapp) that contain everything you need (e.g. asm folder), or two archives. Barring that, the page should at least list the dependency on asm, have a link to download the jars, and instructions on where they need to go.

**Comment by tobespc** [comment]
@deboer-tim I agree Tim, will make those changes

**Comment by robbinspg** [comment]
https://github.com/RuntimeTools/javametrics/pull/63 creates the new release zip that includes asm etc.
